apiVersion: v1
kind: Service
metadata:
  name: squash-server
  namespace: '{{ meta.namespace }}'
spec:
  ports:
    - name: http-squash-api
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: squash-server