apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: squashes.squash.example.com
spec:
  group: squash.example.com
  names:
    kind: Squash
    listKind: SquashList
    plural: squashes
    singular: squash
  scope: Namespaced
  version: v1alpha1
